name: 'Trabalho final - CI de nível 01'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        #Setup da versão do node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Instalação do npm
        run: npm install

      - name: Instalando o Cypress
        run: npm run cy-run

      #caso dê erro em algum teste, o continue irá seguir executando os demais testes
        continue-on-error: true

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          run: npm run report-merge

      - name: Relatório de testes
        run: npm run report-mocha 
